[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run db:migrate && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.envs]
NODE_ENV = "production" 