// Shared styles for the hotel reservation app
export const styles = {
  appBg: {
    minHeight: '100vh',
    background: `url('https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1500&q=80') center center / cover no-repeat fixed`,
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
  },
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100vw',
    height: '100vh',
    background: 'rgba(30, 42, 73, 0.65)',
    zIndex: 0,
    pointerEvents: 'none',
  },
  layout: {
    display: 'flex',
    flex: 1,
    width: '100%',
    minHeight: 'calc(100vh - 120px)',
  },
  sidebar: {
    width: 220,
    minWidth: 180,
    background: 'rgba(255,255,255,0.97)',
    borderRight: '1.5px solid #1976d2',
    boxShadow: '2px 0 8px #0001',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    padding: '2rem 0 2rem 0',
    zIndex: 2,
  },
  sidebarTab: (isActive) => ({
    background: isActive ? '#1976d2' : '#fff',
    color: isActive ? '#fff' : '#1976d2',
    border: 'none',
    borderLeft: isActive ? '4px solid #1565c0' : '4px solid transparent',
    borderRadius: '0 24px 24px 0',
    margin: '0 0 12px 0',
    textAlign: 'left',
    fontWeight: isActive ? 700 : 500,
    fontSize: 18,
    padding: '12px 24px',
    boxShadow: isActive ? '0 2px 8px #1976d222' : 'none',
    transition: 'all 0.2s',
    cursor: 'pointer',
  }),
  mainContent: {
    flex: 1,
    width: '100%',
    padding: '0 0',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    zIndex: 1,
  },
  card: {
    background: 'rgba(255,255,255,0.95)',
    borderRadius: 8,
    boxShadow: '0 2px 16px #0002',
    padding: 24,
    margin: '2rem 0',
    width: 600,
    minWidth: 600,
    maxWidth: 600,
  },
  btn: {
    background: '#1976d2',
    color: '#fff',
    border: 'none',
    borderRadius: 4,
    padding: '6px 16px',
    cursor: 'pointer',
    marginLeft: 8,
  },
  navBtn: {
    background: '#fff',
    color: '#1976d2',
    border: '1px solid #1976d2',
    borderRadius: 4,
    padding: '6px 16px',
    cursor: 'pointer',
    marginLeft: 0,
    marginRight: 8,
  },
  input: {
    padding: 8,
    borderRadius: 4,
    border: '1px solid #ccc',
    marginRight: 8,
    marginBottom: 8,
  },
  header: {
    background: '#1976d2',
    color: '#fff',
    padding: '1.5rem 0',
    textAlign: 'center',
    marginBottom: 24,
    boxShadow: '0 2px 8px #0002',
  },
  footer: {
    background: '#1976d2',
    color: '#fff',
    textAlign: 'center',
    padding: '1rem 0',
    marginTop: 40,
  },
  errorMessage: {
    color: 'red',
    marginBottom: 8,
  },
  emptyState: {
    color: '#b71c1c',
    background: '#fff3e0',
    border: '1px solid #ffccbc',
    borderRadius: 8,
    padding: 16,
    textAlign: 'center',
    marginTop: 16,
    fontWeight: 500,
    fontSize: 18,
  },
  userItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  userInfo: {
    color: '#222',
    background: '#e3f2fd',
    padding: '4px 8px',
    borderRadius: 4,
    flex: 1,
  },
  deleteBtn: {
    background: '#e53935',
    marginLeft: 8,
  },
}; 